/*
 * ADC_interface.h
 *
 * Created: 18/09/2021 08:33:01 م
 *  Author: Ali Emad
 */ 

#ifndef ADC_INTERFACE_H_INCLUDED
#define ADC_INTERFACE_H_INCLUDED

enum ADC_Mode_t{
	ADC_MODE_SINGLE_CONVERSION,
	ADC_MODE_COUNTINOUS_CONVERSION
};

enum ADC_Prescalar_t{
	ADC_PRESCALAR_DIV_2 = 1,
	ADC_PRESCALAR_DIV_4,
	ADC_PRESCALAR_DIV_8,
	ADC_PRESCALAR_DIV_16,
	ADC_PRESCALAR_DIV_32,
	ADC_PRESCALAR_DIV_64,
	ADC_PRESCALAR_DIV_128
};

enum ADC_AutoTrigger_t{
	ADC_AUTO_TRIGGER_FREE_RUNNING,
	ADC_AUTO_TRIGGER_ANALOG_COMPARATOR,
	ADC_AUTO_TRIGGER_EXTI0,
	ADC_AUTO_TRIGGER_TIM0_COMPARE_MATCH,
	ADC_AUTO_TRIGGER_OVERFLOW,
	ADC_AUTO_TRIGGER_TIM1_COMPAE_MATCH_B,
	ADC_AUTO_TRIGGER_TIM1_OVERFLOW,
	ADC_AUTO_TRIGGER_TIM1_CAPTURE_EVENT
};

enum ADC_ChannelID_t{
	ADC_CHANNEL_SINGLE_0,
	ADC_CHANNEL_SINGLE_1,
	ADC_CHANNEL_SINGLE_2,
	ADC_CHANNEL_SINGLE_3,
	ADC_CHANNEL_SINGLE_4,
	ADC_CHANNEL_SINGLE_5,
	ADC_CHANNEL_SINGLE_6,
	ADC_CHANNEL_SINGLE_7,
	ADC_CHANNEL_DIFF_0_0_GAIN_10,
	ADC_CHANNEL_DIFF_1_0_GAIN_10,
	ADC_CHANNEL_DIFF_0_0_GAIN_200,
	ADC_CHANNEL_DIFF_1_0_GAIN_200,
	ADC_CHANNEL_DIFF_2_2_GAIN_10,
	ADC_CHANNEL_DIFF_3_2_GAIN_10,
	ADC_CHANNEL_DIFF_2_2_GAIN_200,
	ADC_CHANNEL_DIFF_3_2_GAIN_200,
	ADC_CHANNEL_DIFF_0_1_GAIN_1,
	ADC_CHANNEL_DIFF_1_1_GAIN_1,
	ADC_CHANNEL_DIFF_2_1_GAIN_1,
	ADC_CHANNEL_DIFF_3_1_GAIN_1,
	ADC_CHANNEL_DIFF_4_1_GAIN_1,
	ADC_CHANNEL_DIFF_5_1_GAIN_1,
	ADC_CHANNEL_DIFF_6_1_GAIN_1,
	ADC_CHANNEL_DIFF_7_1_GAIN_1,
	ADC_CHANNEL_DIFF_0_2_GAIN_1,
	ADC_CHANNEL_DIFF_1_2_GAIN_1,
	ADC_CHANNEL_DIFF_2_2_GAIN_1,
	ADC_CHANNEL_DIFF_3_2_GAIN_1,
	ADC_CHANNEL_DIFF_4_2_GAIN_1,
	ADC_CHANNEL_DIFF_5_2_GAIN_1,
	ADC_CHANNEL_SINGLE_1_22V,
	ADC_CHANNEL_SINGLE_GND,

};

void MADC_voidInit(enum ADC_Mode_t Mode, enum ADC_Prescalar_t);

void MADC_voidSetAutoTriggerSource(enum ADC_AutoTrigger_t TriggerSource);

u16 MADC_u16ReadChannelSynch(enum ADC_ChannelID_t Channel);

void MADC_voidReadChannelAsynch(enum ADC_ChannelID_t Channel, void (*CallBack)(u16 ReadValue));

void MADC_voidStartContinousMode(void);

void MADC_voidStopContinousMode(void);

#endif
